# Generated by Django 2.2.1 on 2019-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20190730_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
