# Generated by Django 2.2.1 on 2019-07-30 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20190730_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
