# Generated by Django 2.2.1 on 2019-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20190730_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='txn_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
